name: CD pipline

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Delete old docker container
        run: sudo docker rm -f backend_container || true
      - name: Remove docker image
        run: sudo docker rmi evify/logistic_backend:latest || true
      - name: Pull docker image
        run: sudo docker pull evify/logistic_backend:latest      
      - name: Run Docker Container
        run: sudo docker run -d -p 8000:8000 --name backend_container  evify/logistic_backend
