on:
  push:
    branchs:
      -master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker image
      run: |
        docker build . --file Dockerfile --tag demo:$(date +%s)

    - name: Test
      run: |
        echo "test"

    - name: deploy
      run: |
        echo "deploy"

   


